### ISSUE TITLE
mini-css-extract-plugin crashes with tagAssetsWithKey

### ISSUE THREAD

**Issue by Austaras** [DanielSchaffer/webpack-babel-multi-target-plugin#90]
When I configured this plugin with
```
targets: {
        modern: true,
        legacy: {
          tagAssetsWithKey: true,
        },
      },
```
`mini-css-extract-plugin` will crash

**Comment by DanielSchaffer** [comment]
@Austaras can you add some more details? (stack trace, package versions, etc)

**Comment by Austaras** [comment]
I'm using master branch of this repo and got
```
ERROR in chunk main [initial]
    main.css
    Cannot read property 'pop' of undefined
    TypeError: Cannot read property 'pop' of undefined
        at MiniCssExtractPlugin.renderContentAsset (/home/chla/Code/webpack-babel-multi-target-plugin/node_modules/mini-css-extract-plugin/dist/index.js:343:44)
        at Object.render (/home/chla/Code/webpack-babel-multi-target-plugin/node_modules/mini-css-extract-plugin/dist/index.js:174:32)
        at Compilation.createChunkAssets (/home/chla/Code/webpack-babel-multi-target-plugin/node_modules/webpack/lib/Compilation.js:2035:29)
        at /home/chla/Code/webpack-babel-multi-target-plugin/node_modules/webpack/lib/Compilation.js:1359:10
        at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/chla/Code/webpack-babel-multi-target-plugin/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
        at AsyncSeriesHook.lazyCompileHook (/home/chla/Code/webpack-babel-multi-target-plugin/node_modules/tapable/lib/Hook.js:154:20)
        at Compilation.seal (/home/chla/Code/webpack-babel-multi-target-plugin/node_modules/webpack/lib/Compilation.js:1304:27)
        at /home/chla/Code/webpack-babel-multi-target-plugin/node_modules/webpack/lib/Compiler.js:665:18
        at /home/chla/Code/webpack-babel-multi-target-plugin/node_modules/webpack/lib/Compilation.js:1224:4
        at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/chla/Code/webpack-babel-multi-target-plugin/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:20:1)
        at AsyncSeriesHook.lazyCompileHook (/home/chla/Code/webpack-babel-multi-target-plugin/node_modules/tapable/lib/Hook.js:154:20)
        at Compilation.finish (/home/chla/Code/webpack-babel-multi-target-plugin/node_modules/webpack/lib/Compilation.js:1216:28)
        at /home/chla/Code/webpack-babel-multi-target-plugin/node_modules/webpack/lib/Compiler.js:662:17
        at _done (eval at create (/home/chla/Code/webpack-babel-multi-target-plugin/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
        at eval (eval at create (/home/chla/Code/webpack-babel-multi-target-plugin/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:31:22)
        at runMicrotasks (<anonymous>)

```
You could test with [this branch](https://github.com/Austaras/webpack-babel-multi-target-plugin/tree/debug)
